trigger:
- master

resources:
- repo: self

variables:

  
  jraptestvariable: 'somevalue'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      name: Hosted VS2017
      demands:
      - msbuild
      - visualstudio
      - vstest
      - java

    #Your build pipeline references an undefined variable named ‘Parameters.solution’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
    #Your build pipeline references an undefined variable named ‘Parameters.solution’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
    #Your build pipeline references the ‘BuildPlatform’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
    #Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
    #Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
    #Your build pipeline references the ‘BuildPlatform’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
    #Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
    #Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
    #Your build pipeline references an undefined variable named ‘Parameters.ArtifactName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 5.0.0'
      inputs:
        versionSpec: 5.0.0

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: '$(Parameters.solution)'

    - task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@4
      displayName: 'Prepare analysis on SonarQube'
      inputs:
        SonarQube: 'Jrap Test SonarQube'
        projectKey: TestProjectKey
        projectName: 'Test Project Key'

    - task: VSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: '$(Parameters.solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'

    - task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@4
      displayName: 'Run Code Analysis'

    - task: SonarSource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@4
      displayName: 'Publish Quality Gate Result'

    - task: PublishSymbols@1
      displayName: 'Publish symbols path'
      inputs:
        SearchPattern: '**\bin\**\*.pdb'
      continueOnError: true

    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        SourceFolder: ArmTemplates
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: '$(Parameters.ArtifactName)'


- stage: Deploy
  displayName: Dev Deploy
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      name: Hosted VS2017
      demands:
      - azureps
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureResourceGroupDeployment@2
              displayName: 'Azure Deployment:Create Azure App Service'
              inputs:
                azureSubscription: 'Visual Studio Professional (05a11ad3-90da-4cd1-89f1-e804bea8bd91)'
                resourceGroupName: jrappel
                location: 'East US 2'
                csmFile: '$(System.DefaultWorkingDirectory)/**/windows-webapp-template.json'
                overrideParameters: '-webAppName jrappersonal -hostingPlanName jrappersonal-plan -appInsightsLocation "South Central US" -sku "S1 Standard"'
            
            - task: DownloadSecureFile@1
              displayName: 'Download secure file'
              inputs:
                secureFile: license.xml
            
            - task: AzureRmWebAppDeployment@4
              displayName: 'Deploy Azure App Service'
              inputs:
                azureSubscription: 'Visual Studio Professional (05a11ad3-90da-4cd1-89f1-e804bea8bd91)'
                WebAppName: jrappersonal
                packageForLinux: '$(System.DefaultWorkingDirectory)\**\*.zip'
                ScriptType: 'Inline Script'
                InlineScript: |
                  set webroot=D:\home\site\wwwroot
                  echo %webroot%
                  del /S *.Release.config
                  copy $(Agent.TempDirectory)\license.xml D:\home\site\wwwroot
                enableCustomDeployment: true
                ExcludeFilesFromAppDataFlag: false
                enableXmlTransform: true
                enableXmlVariableSubstitution: true
            
            - task: VisualStudioTestPlatformInstaller@1
              displayName: 'Visual Studio Test Platform Installer'

            - task: AzurePowerShell@3
              displayName: 'Azure PowerShell script: InlineScript'
              inputs:
                azureSubscription: 'Visual Studio Professional (05a11ad3-90da-4cd1-89f1-e804bea8bd91)'
                ScriptType: InlineScript
                azurePowerShellVersion: LatestVersion